# Generated by Django 5.1.3 on 2024-11-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tagsarticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagsarticles',
            name='is_main',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
