# Generated by Django 5.1.3 on 2024-11-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_tags_tagsarticles_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsarticles',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.tags'),
        ),
    ]
