# Generated by Django 5.1.3 on 2024-11-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_tagsarticles_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsarticles',
            name='Article',
        ),
        migrations.AlterField(
            model_name='tagsarticles',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.tags'),
        ),
        migrations.AddField(
            model_name='tagsarticles',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
            preserve_default=False,
        ),
    ]
