# Generated by Django 5.1.4 on 2024-12-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturemeasurment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
