# Generated by Django 5.1.4 on 2024-12-07 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_temperaturemeasurment_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturemeasurment',
            name='sensor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor'),
            preserve_default=False,
        ),
    ]
