# Generated by Django 5.1.4 on 2024-12-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_alter_temperaturemeasurment_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturemeasurment',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurments', to='measurement.sensor'),
        ),
    ]
