# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP33",
  "description": "Датчик в спальне"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/2/
Content-Type: application/json

{
  "description": "Перенес датчик перед холодильником"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 28.3
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/2/
Content-Type: application/json


###
GET {{baseUrl}}/measurements/
Content-Type: application/json